### ISSUE TITLE
On RS****CN track 

### ISSUE THREAD

**Issue by infernvs** [hdnpt/geartrack-website#11] opened 2017-04-27 08:11 UTC
GET /img/loading.svg 304 0.655 ms - -
GET /img/timeline_line.png 304 0.556 ms - -
events.js:160
      throw er; // Unhandled 'error' event
      ^

Error: spawn /home/cerbervs/geartrack-website/node_modules/htmltidy/bin/linux/tidy ENOENT
    at exports._errnoException (util.js:1018:11)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:193:32)
    at onErrorNT (internal/child_process.js:367:16)
    at _combinedTickCallback (internal/process/next_tick.js:80:11)
    at process._tickCallback (internal/process/next_tick.js:104:9)

npm ERR! Linux 3.16.0-4-amd64
npm ERR! argv "/usr/bin/nodejs" "/usr/bin/npm" "start"
npm ERR! node v6.10.2
npm ERR! npm  v3.10.10
npm ERR! code ELIFECYCLE
npm ERR! geartrack-website@1.0.2 start: `node ./bin/www`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the geartrack-website@1.0.2 start script 'node ./bin/www'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the geartrack-website package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node ./bin/www
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs geartrack-website
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls geartrack-website
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /home/cerbervs/geartrack-website/npm-debug.log

**Comment by iamfreee** [comment] 2017-04-27 12:07
Hi,

That error was caused by a dependency in the geartrack package:
https://github.com/hdnpt/geartrack/blob/master/package.json#L26

It is fixed in the latest versions, you should run `npm update`

😃

**Closed by iamfreee** 2017-04-27 12:07 UTC
